CREATE TABLE [dbo].[TLRM_INV_IMSIIPs_BACKUP] (
  [imsi] [varchar](250) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
  [ip] [varchar](250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  CONSTRAINT [PK_TLRM_INV-IMSIIPs_BACKUP] PRIMARY KEY CLUSTERED ([imsi])
)
ON [PRIMARY]
GO